version: '3'

volumes:
  django_media: {}
  postgres_data: {}
  postgres_data_backups: {}
  traefik: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: reddit_liv_django
    volumes:
      - django_media:/app/reddit/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.liv/.django
      - ./.envs/.liv/.postgres
    command: /start
    restart: unless-stopped
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: reddit_liv_nginx
    depends_on:
      - django
    volumes:
      - django_media:/usr/share/nginx/media:ro
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: reddit_liv_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.liv/.postgres
    restart: unless-stopped

  traefik:
    build:
      context: .
      dockerfile: ./compose/liv/traefik/Dockerfile
    image: reddit_liv_traefik
    depends_on:
      - django
    volumes:
        - traefik:/etc/traefik/acme:z
    ports:
      - '127.0.0.1:8201:80'
    restart: unless-stopped

  redis:
    image: redis:5.0
    restart: unless-stopped
