version: '3'

volumes:
  production_django_media: {}
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: reddit_production_django
    volumes:
      - production_django_media:/app/reddit/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    restart: unless-stopped
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: reddit_production_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: reddit_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
    restart: unless-stopped

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: reddit_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    restart: unless-stopped

  redis:
    image: redis:5.0
    restart: unless-stopped
